version: '3.9'

services:
  mcp:
    build:
      context: ./mcp
    container_name: mcp-server
    ports:
      - "3001:3001"
    env_file:
      - ./mcp/.env
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    container_name: ollama
    ports:
      - "11500:11500"
    volumes:
      - ollama-data:/root/.ollama
    environment:
      - OLLAMA_MODELS=llama3.2:latest

  admin-portal:
    build:
      context: ./admin-portal
    container_name: admin-portal
    ports:
      - "3000:3000"
    env_file:
      - ./admin-portal/.env.local
    depends_on:
      - mcp

volumes:
  ollama-data:
